import { BoardTemplate } from '../types/board';

export const BOARD_TEMPLATES: BoardTemplate[] = [
  {
    id: 'retro-brainstorm',
    title: 'Ретроспектива и Брейншторминг',
    category: 'Agile & Команда',
    description: 'Классическая командная ретроспектива: Что прошло отлично, Что улучшить, Новые идеи и Действия.',
    badge: 'Популярно',
    elements: [
      // Frame 1: Что прошло хорошо
      {
        id: 'frame-1',
        type: 'frame',
        x: 80,
        y: 80,
        width: 380,
        height: 640,
        zIndex: 1,
        frameTitle: '🟢 Что сработало отлично',
        fill: '#f0fdf4',
        stroke: '#86efac',
        strokeWidth: 2,
      },
      {
        id: 'sticky-1-1',
        type: 'sticky',
        x: 105,
        y: 150,
        width: 155,
        height: 155,
        zIndex: 10,
        stickyColor: 'green',
        text: 'Выкатили релиз v2.4 точно в срок без единого критического бага! 🚀',
        fontSize: 14,
        textAlign: 'center',
        frameId: 'frame-1',
      },
      {
        id: 'sticky-1-2',
        type: 'sticky',
        x: 280,
        y: 150,
        width: 155,
        height: 155,
        zIndex: 11,
        stickyColor: 'yellow',
        text: 'Новый онбординг поднял конверсию регистрации на 18% 🎉',
        fontSize: 14,
        textAlign: 'center',
        frameId: 'frame-1',
      },
      {
        id: 'sticky-1-3',
        type: 'sticky',
        x: 105,
        y: 325,
        width: 155,
        height: 155,
        zIndex: 12,
        stickyColor: 'green',
        text: 'Синхронизация между фронтендом и бэкендом прошла гладко ⚡',
        fontSize: 14,
        textAlign: 'center',
        frameId: 'frame-1',
      },
      {
        id: 'sticky-1-4',
        type: 'sticky',
        x: 280,
        y: 325,
        width: 155,
        height: 155,
        zIndex: 13,
        stickyColor: 'blue',
        text: 'Команда оперативно закрыла все замечания по безопасности 🛡️',
        fontSize: 14,
        textAlign: 'center',
        frameId: 'frame-1',
      },

      // Frame 2: Что можно улучшить
      {
        id: 'frame-2',
        type: 'frame',
        x: 500,
        y: 80,
        width: 380,
        height: 640,
        zIndex: 2,
        frameTitle: '🟠 Что можно улучшить',
        fill: '#fffbeb',
        stroke: '#fcd34d',
        strokeWidth: 2,
      },
      {
        id: 'sticky-2-1',
        type: 'sticky',
        x: 525,
        y: 150,
        width: 155,
        height: 155,
        zIndex: 14,
        stickyColor: 'orange',
        text: 'Долгие code review — пуллреквесты висели по 3 дня ⏳',
        fontSize: 14,
        textAlign: 'center',
        frameId: 'frame-2',
      },
      {
        id: 'sticky-2-2',
        type: 'sticky',
        x: 700,
        y: 150,
        width: 155,
        height: 155,
        zIndex: 15,
        stickyColor: 'pink',
        text: 'Не хватало детальных спецификаций по мобильной версии 📱',
        fontSize: 14,
        textAlign: 'center',
        frameId: 'frame-2',
      },
      {
        id: 'sticky-2-3',
        type: 'sticky',
        x: 525,
        y: 325,
        width: 155,
        height: 155,
        zIndex: 16,
        stickyColor: 'orange',
        text: 'Тестовый контур иногда падал под высокой нагрузкой 📉',
        fontSize: 14,
        textAlign: 'center',
        frameId: 'frame-2',
      },
      {
        id: 'sticky-2-4',
        type: 'sticky',
        x: 700,
        y: 325,
        width: 155,
        height: 155,
        zIndex: 17,
        stickyColor: 'yellow',
        text: 'Нужно заранее предупреждать дизайн-отдел о срочных правках 🔔',
        fontSize: 14,
        textAlign: 'center',
        frameId: 'frame-2',
      },

      // Frame 3: Новые идеи
      {
        id: 'frame-3',
        type: 'frame',
        x: 920,
        y: 80,
        width: 380,
        height: 640,
        zIndex: 3,
        frameTitle: '💡 Новые идеи',
        fill: '#eff6ff',
        stroke: '#93c5fd',
        strokeWidth: 2,
      },
      {
        id: 'sticky-3-1',
        type: 'sticky',
        x: 945,
        y: 150,
        width: 155,
        height: 155,
        zIndex: 18,
        stickyColor: 'blue',
        text: 'Внедрить автоматический линтинг и тесты в CI/CD перед ревью 🤖',
        fontSize: 14,
        textAlign: 'center',
        frameId: 'frame-3',
      },
      {
        id: 'sticky-3-2',
        type: 'sticky',
        x: 1120,
        y: 150,
        width: 155,
        height: 155,
        zIndex: 19,
        stickyColor: 'purple',
        text: 'Сделать еженедельный демо-день для всех стейкхолдеров 🎤',
        fontSize: 14,
        textAlign: 'center',
        frameId: 'frame-3',
      },
      {
        id: 'sticky-3-3',
        type: 'sticky',
        x: 945,
        y: 325,
        width: 155,
        height: 155,
        zIndex: 20,
        stickyColor: 'green',
        text: 'Ввести парное программирование для сложных фичей 👥',
        fontSize: 14,
        textAlign: 'center',
        frameId: 'frame-3',
      },
      {
        id: 'sticky-3-4',
        type: 'sticky',
        x: 1120,
        y: 325,
        width: 155,
        height: 155,
        zIndex: 21,
        stickyColor: 'pink',
        text: 'Запустить внутренний хакатон по автоматизации рутины 🚀',
        fontSize: 14,
        textAlign: 'center',
        frameId: 'frame-3',
      },

      // Frame 4: План действий
      {
        id: 'frame-4',
        type: 'frame',
        x: 1340,
        y: 80,
        width: 380,
        height: 640,
        zIndex: 4,
        frameTitle: '🎯 План действий (Action Items)',
        fill: '#faf5ff',
        stroke: '#d8b4fe',
        strokeWidth: 2,
      },
      {
        id: 'card-4-1',
        type: 'card',
        x: 1365,
        y: 150,
        width: 330,
        height: 125,
        zIndex: 22,
        cardTitle: 'Настроить SLA для Code Review (макс 24ч)',
        cardDescription: 'Ответственный: Алексей. Обсудить на командном синке во вторник.',
        cardTag: 'Процессы',
        cardTagColor: '#6366f1',
        cardStatus: 'in_progress',
        cardAssignee: { name: 'Алексей', avatarColor: '#3b82f6' },
        frameId: 'frame-4',
      },
      {
        id: 'card-4-2',
        type: 'card',
        x: 1365,
        y: 295,
        width: 330,
        height: 125,
        zIndex: 23,
        cardTitle: 'Обновить документацию API по вебхукам',
        cardDescription: 'Подготовить примеры запросов в Swagger/OpenAPI.',
        cardTag: 'Dev',
        cardTagColor: '#10b981',
        cardStatus: 'todo',
        cardAssignee: { name: 'Елена', avatarColor: '#ec4899' },
        frameId: 'frame-4',
      },
      {
        id: 'card-4-3',
        type: 'card',
        x: 1365,
        y: 440,
        width: 330,
        height: 125,
        zIndex: 24,
        cardTitle: 'Подготовить демо прототипа новой дизайн-системы',
        cardDescription: 'Согласовать компоненты интерфейса с продуктовыми лидами.',
        cardTag: 'Дизайн',
        cardTagColor: '#ec4899',
        cardStatus: 'todo',
        cardAssignee: { name: 'Анна', avatarColor: '#8b5cf6' },
        frameId: 'frame-4',
      },
    ],
  },
  {
    id: 'kanban-board',
    title: 'Канбан-доска проектов',
    category: 'Управление задачами',
    description: 'Удобная доска со статусами Бэклог, В работе, Тестирование и Завершено с карточками задач.',
    badge: 'Канбан',
    elements: [
      {
        id: 'k-frame-1',
        type: 'frame',
        x: 100,
        y: 100,
        width: 320,
        height: 680,
        zIndex: 1,
        frameTitle: '📋 Бэклог (To Do)',
        fill: '#f8fafc',
        stroke: '#cbd5e1',
        strokeWidth: 2,
      },
      {
        id: 'k-card-1',
        type: 'card',
        x: 120,
        y: 160,
        width: 280,
        height: 130,
        zIndex: 10,
        cardTitle: 'Интеграция с Google Drive',
        cardDescription: 'Возможность сохранять экспорт напрямую на облачный диск пользователя.',
        cardTag: 'Интеграции',
        cardTagColor: '#3b82f6',
        cardStatus: 'todo',
        cardAssignee: { name: 'Дмитрий', avatarColor: '#10b981' },
      },
      {
        id: 'k-card-2',
        type: 'card',
        x: 120,
        y: 310,
        width: 280,
        height: 130,
        zIndex: 11,
        cardTitle: 'Поддержка горячих клавиш Ctrl+D',
        cardDescription: 'Быстрое дублирование выделенного элемента со смещением в 20px.',
        cardTag: 'UX/UI',
        cardTagColor: '#8b5cf6',
        cardStatus: 'todo',
        cardAssignee: { name: 'София', avatarColor: '#f59e0b' },
      },

      {
        id: 'k-frame-2',
        type: 'frame',
        x: 450,
        y: 100,
        width: 320,
        height: 680,
        zIndex: 2,
        frameTitle: '⚡ В процессе (In Progress)',
        fill: '#eff6ff',
        stroke: '#93c5fd',
        strokeWidth: 2,
      },
      {
        id: 'k-card-3',
        type: 'card',
        x: 470,
        y: 160,
        width: 280,
        height: 130,
        zIndex: 12,
        cardTitle: 'Умные стрелки и коннекторы',
        cardDescription: 'Привязка стрелок к 4 якорным точкам фигур (магнитное прилипание).',
        cardTag: 'Canvas Core',
        cardTagColor: '#ef4444',
        cardStatus: 'in_progress',
        cardAssignee: { name: 'Максим', avatarColor: '#3b82f6' },
      },

      {
        id: 'k-frame-3',
        type: 'frame',
        x: 800,
        y: 100,
        width: 320,
        height: 680,
        zIndex: 3,
        frameTitle: '🧪 Тестирование (Review)',
        fill: '#fffbeb',
        stroke: '#fcd34d',
        strokeWidth: 2,
      },
      {
        id: 'k-card-4',
        type: 'card',
        x: 820,
        y: 160,
        width: 280,
        height: 130,
        zIndex: 13,
        cardTitle: 'Экспорт доски в PNG и SVG',
        cardDescription: 'Проверить рендеринг на Retina-экранах при масштабировании.',
        cardTag: 'QA',
        cardTagColor: '#d97706',
        cardStatus: 'in_progress',
        cardAssignee: { name: 'Анна', avatarColor: '#ec4899' },
      },

      {
        id: 'k-frame-4',
        type: 'frame',
        x: 1150,
        y: 100,
        width: 320,
        height: 680,
        zIndex: 4,
        frameTitle: '✅ Завершено (Done)',
        fill: '#f0fdf4',
        stroke: '#86efac',
        strokeWidth: 2,
      },
      {
        id: 'k-card-5',
        type: 'card',
        x: 1170,
        y: 160,
        width: 280,
        height: 130,
        zIndex: 14,
        cardTitle: 'Бесконечный зум и панорамирование',
        cardDescription: 'Поддержка скролла тачпада, зажатия пробела и колесика мыши.',
        cardTag: 'Архитектура',
        cardTagColor: '#10b981',
        cardStatus: 'done',
        cardAssignee: { name: 'Иван', avatarColor: '#6366f1' },
      },
    ],
  },
  {
    id: 'system-flowchart',
    title: 'Архитектура сервиса & Flowchart',
    category: 'Диаграммы & Архитектура',
    description: 'Интерактивная блок-схема с соединенными стрелками: клиент, API Gateway, микросервисы и база данных.',
    badge: 'Схема',
    elements: [
      {
        id: 'node-client',
        type: 'shape',
        shapeType: 'rounded',
        x: 120,
        y: 280,
        width: 170,
        height: 90,
        zIndex: 10,
        fill: '#e0e7ff',
        stroke: '#6366f1',
        strokeWidth: 2,
        text: 'Клиентское SPA\n(React + Tailwind)',
        fontSize: 14,
        fontColor: '#1e1b4b',
        isBold: true,
      },
      {
        id: 'node-gateway',
        type: 'shape',
        shapeType: 'rectangle',
        x: 390,
        y: 280,
        width: 180,
        height: 90,
        zIndex: 11,
        fill: '#fef3c7',
        stroke: '#f59e0b',
        strokeWidth: 2,
        text: 'API Gateway &\nLoad Balancer',
        fontSize: 14,
        fontColor: '#78350f',
        isBold: true,
      },
      {
        id: 'node-auth',
        type: 'shape',
        shapeType: 'rectangle',
        x: 690,
        y: 140,
        width: 190,
        height: 80,
        zIndex: 12,
        fill: '#dcfce7',
        stroke: '#22c55e',
        strokeWidth: 2,
        text: 'Auth Service\n(JWT & Sessions)',
        fontSize: 14,
        fontColor: '#14532d',
        isBold: true,
      },
      {
        id: 'node-core',
        type: 'shape',
        shapeType: 'rectangle',
        x: 690,
        y: 280,
        width: 190,
        height: 90,
        zIndex: 13,
        fill: '#e0f2fe',
        stroke: '#0284c7',
        strokeWidth: 2,
        text: 'Core Canvas API\n(CRDT Sync Engine)',
        fontSize: 14,
        fontColor: '#0c4a6e',
        isBold: true,
      },
      {
        id: 'node-db',
        type: 'shape',
        shapeType: 'cylinder',
        x: 1000,
        y: 270,
        width: 160,
        height: 110,
        zIndex: 14,
        fill: '#f3e8ff',
        stroke: '#a855f7',
        strokeWidth: 2,
        text: 'PostgreSQL\nБаза данных',
        fontSize: 14,
        fontColor: '#581c87',
        isBold: true,
      },
      // Connectors
      {
        id: 'conn-1',
        type: 'connector',
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        zIndex: 5,
        fromId: 'node-client',
        toId: 'node-gateway',
        fromAnchor: 'right',
        toAnchor: 'left',
        lineType: 'orthogonal',
        arrowEnd: true,
        stroke: '#475569',
        strokeWidth: 2,
        connectorLabel: 'HTTPS / WSS',
      },
      {
        id: 'conn-2',
        type: 'connector',
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        zIndex: 6,
        fromId: 'node-gateway',
        toId: 'node-auth',
        fromAnchor: 'top',
        toAnchor: 'left',
        lineType: 'curved',
        arrowEnd: true,
        stroke: '#475569',
        strokeWidth: 2,
        connectorLabel: 'Проверка прав',
      },
      {
        id: 'conn-3',
        type: 'connector',
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        zIndex: 7,
        fromId: 'node-gateway',
        toId: 'node-core',
        fromAnchor: 'right',
        toAnchor: 'left',
        lineType: 'straight',
        arrowEnd: true,
        stroke: '#475569',
        strokeWidth: 2,
        connectorLabel: 'Операции',
      },
      {
        id: 'conn-4',
        type: 'connector',
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        zIndex: 8,
        fromId: 'node-core',
        toId: 'node-db',
        fromAnchor: 'right',
        toAnchor: 'left',
        lineType: 'straight',
        arrowEnd: true,
        stroke: '#475569',
        strokeWidth: 2,
        connectorLabel: 'Сохранение',
      },
    ],
  },
  {
    id: 'swot-analysis',
    title: 'SWOT-анализ стратегии',
    category: 'Бизнес-стратегия',
    description: 'Матрица из 4 квадрантов: Сильные стороны (S), Слабые (W), Возможности (O) и Угрозы (T).',
    badge: 'Бизнес',
    elements: [
      {
        id: 'swot-s',
        type: 'frame',
        x: 100,
        y: 100,
        width: 440,
        height: 380,
        zIndex: 1,
        frameTitle: '💪 Strengths (Сильные стороны)',
        fill: '#f0fdf4',
        stroke: '#4ade80',
        strokeWidth: 2,
      },
      {
        id: 'swot-sticky-s1',
        type: 'sticky',
        x: 130,
        y: 180,
        width: 170,
        height: 140,
        zIndex: 10,
        stickyColor: 'green',
        text: 'Высокая скорость работы и интуитивный интерфейс в браузере ⚡',
        fontSize: 14,
        textAlign: 'center',
        frameId: 'swot-s',
      },
      {
        id: 'swot-sticky-s2',
        type: 'sticky',
        x: 330,
        y: 180,
        width: 170,
        height: 140,
        zIndex: 11,
        stickyColor: 'yellow',
        text: 'Сплоченная опытная команда разработчиков и сильная экспертиза 🎯',
        fontSize: 14,
        textAlign: 'center',
        frameId: 'swot-s',
      },
      {
        id: 'swot-w',
        type: 'frame',
        x: 580,
        y: 100,
        width: 440,
        height: 380,
        zIndex: 2,
        frameTitle: '⚠️ Weaknesses (Слабые стороны)',
        fill: '#fff1f2',
        stroke: '#f87171',
        strokeWidth: 2,
      },
      {
        id: 'swot-sticky-w1',
        type: 'sticky',
        x: 610,
        y: 180,
        width: 170,
        height: 140,
        zIndex: 12,
        stickyColor: 'pink',
        text: 'Пока нет нативных мобильных приложений под iOS/Android 📱',
        fontSize: 14,
        textAlign: 'center',
        frameId: 'swot-w',
      },
      {
        id: 'swot-sticky-w2',
        type: 'sticky',
        x: 810,
        y: 180,
        width: 170,
        height: 140,
        zIndex: 13,
        stickyColor: 'orange',
        text: 'Ограниченный маркетинговый бюджет на первом этапе 📉',
        fontSize: 14,
        textAlign: 'center',
        frameId: 'swot-w',
      },
      {
        id: 'swot-o',
        type: 'frame',
        x: 100,
        y: 520,
        width: 440,
        height: 380,
        zIndex: 3,
        frameTitle: '🚀 Opportunities (Возможности)',
        fill: '#eff6ff',
        stroke: '#60a5fa',
        strokeWidth: 2,
      },
      {
        id: 'swot-sticky-o1',
        type: 'sticky',
        x: 130,
        y: 600,
        width: 170,
        height: 140,
        zIndex: 14,
        stickyColor: 'blue',
        text: 'Растущий рынок удаленной работы и потребность в коллаборации 🌍',
        fontSize: 14,
        textAlign: 'center',
        frameId: 'swot-o',
      },
      {
        id: 'swot-sticky-o2',
        type: 'sticky',
        x: 330,
        y: 600,
        width: 170,
        height: 140,
        zIndex: 15,
        stickyColor: 'green',
        text: 'Партнерство с образовательными платформами и EdTech 🎓',
        fontSize: 14,
        textAlign: 'center',
        frameId: 'swot-o',
      },
      {
        id: 'swot-t',
        type: 'frame',
        x: 580,
        y: 520,
        width: 440,
        height: 380,
        zIndex: 4,
        frameTitle: '🛡️ Threats (Угрозы & Риски)',
        fill: '#faf5ff',
        stroke: '#c084fc',
        strokeWidth: 2,
      },
      {
        id: 'swot-sticky-t1',
        type: 'sticky',
        x: 610,
        y: 600,
        width: 170,
        height: 140,
        zIndex: 16,
        stickyColor: 'purple',
        text: 'Высокая конкуренция со стороны устоявшихся гигантов 🏢',
        fontSize: 14,
        textAlign: 'center',
        frameId: 'swot-t',
      },
      {
        id: 'swot-sticky-t2',
        type: 'sticky',
        x: 810,
        y: 600,
        width: 170,
        height: 140,
        zIndex: 17,
        stickyColor: 'pink',
        text: 'Колебания валютных курсов и инфраструктурных затрат на серверы 💳',
        fontSize: 14,
        textAlign: 'center',
        frameId: 'swot-t',
      },
    ],
  },
];
